// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { OidcClientMetadata } from '../foundations';

import { ApplicationType } from './custom-types';

export type ApplicationDBEntry = {
  id: string;
  name: string;
  type: ApplicationType;
  oidcClientId: string;
  oidcClientMetadata: OidcClientMetadata;
  createdAt: number;
};

export const Applications = Object.freeze({
  table: 'applications',
  fields: {
    id: 'id',
    name: 'name',
    type: 'type',
    oidcClientId: 'oidc_client_id',
    oidcClientMetadata: 'oidc_client_metadata',
    createdAt: 'created_at',
  },
  fieldKeys: ['id', 'name', 'type', 'oidcClientId', 'oidcClientMetadata', 'createdAt'],
} as const);
