// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { ArbitraryObject, arbitraryObjectGuard, GeneratedSchema, Guard } from '../foundations';

export type CreateConnector = {
  id: string;
  target: string;
  platform?: string | null;
  enabled?: boolean;
  config?: ArbitraryObject;
  createdAt?: number;
};

export type Connector = {
  id: string;
  target: string;
  platform: string | null;
  enabled: boolean;
  config: ArbitraryObject;
  createdAt: number;
};

const createGuard: Guard<CreateConnector> = z.object({
  id: z.string(),
  target: z.string(),
  platform: z.string().nullable().optional(),
  enabled: z.boolean().optional(),
  config: arbitraryObjectGuard.optional(),
  createdAt: z.number().optional(),
});

export const Connectors: GeneratedSchema<CreateConnector> = Object.freeze({
  table: 'connectors',
  tableSingular: 'connector',
  fields: {
    id: 'id',
    target: 'target',
    platform: 'platform',
    enabled: 'enabled',
    config: 'config',
    createdAt: 'created_at',
  },
  fieldKeys: ['id', 'target', 'platform', 'enabled', 'config', 'createdAt'],
  createGuard,
});
