// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export enum ApplicationType {
  Native = 'Native',
  SPA = 'SPA',
  Traditional = 'Traditional',
}
export enum ConnectorType {
  SMS = 'SMS',
  Email = 'Email',
  Social = 'Social',
}
export enum SignAlgorithmType {
  RS256 = 'RS256',
}
export enum AccessTokenFormatType {
  jwt = 'jwt',
}
export enum UserLogType {
  SignInUsernameAndPassword = 'SignInUsernameAndPassword',
  ExchangeAccessToken = 'ExchangeAccessToken',
}
export enum UserLogResult {
  Success = 'Success',
  Failed = 'Failed',
}
export enum PasswordEncryptionMethod {
  SaltAndPepper = 'SaltAndPepper',
}
