// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export enum ApplicationType {
  Native = 'Native',
  SPA = 'SPA',
  Traditional = 'Traditional',
}
export enum LogType {
  SignInUsernameAndPassword = 'SignInUsernameAndPassword',
  ExchangeAccessToken = 'ExchangeAccessToken',
}
export enum LogResult {
  Success = 'Success',
  Failed = 'Failed',
}
export enum PasswordEncryptionMethod {
  SaltAndPepper = 'SaltAndPepper',
}
