// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export enum ApplicationType {
  Native = 'Native',
  SPA = 'SPA',
  Traditional = 'Traditional',
}
export enum PasscodeType {
  SignIn = 'SignIn',
  Register = 'Register',
  ForgotPassword = 'ForgotPassword',
}
export enum UserLogType {
  SignInUsernameAndPassword = 'SignInUsernameAndPassword',
  SignInEmail = 'SignInEmail',
  ExchangeAccessToken = 'ExchangeAccessToken',
}
export enum UserLogResult {
  Success = 'Success',
  Failed = 'Failed',
}
export enum PasswordEncryptionMethod {
  SaltAndPepper = 'SaltAndPepper',
}
