// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export type OidcModelInstanceDBEntry = {
  modelName: string;
  id: string;
  payload: Record<string, unknown>;
  expiresAt: number;
  userCode?: string;
  uid?: string;
  grantId?: string;
};
