// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { OidcClientMetadata } from '../foundations';

export type OidcClientDBEntry = {
  clientId: string;
  metadata: OidcClientMetadata;
  createdAt: number;
};

export const OidcClients = Object.freeze({
  table: 'oidc_clients',
  fields: {
    clientId: 'client_id',
    metadata: 'metadata',
    createdAt: 'created_at',
  },
  fieldKeys: ['clientId', 'metadata', 'createdAt'],
} as const);
