// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export type OidcModelInstanceDBEntry = {
  modelName: string;
  id: string;
  payload: Record<string, unknown>;
  expiresAt: number;
  consumedAt?: number;
  userCode?: string;
  uid?: string;
  grantId?: string;
};

export const OidcModelInstances = Object.freeze({
  table: 'oidc_model_instances',
  fields: {
    modelName: 'model_name',
    id: 'id',
    payload: 'payload',
    expiresAt: 'expires_at',
    consumedAt: 'consumed_at',
    userCode: 'user_code',
    uid: 'uid',
    grantId: 'grant_id',
  },
  fieldKeys: [
    'modelName',
    'id',
    'payload',
    'expiresAt',
    'consumedAt',
    'userCode',
    'uid',
    'grantId',
  ],
} as const);
