// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { GeneratedSchema, Guard } from '../foundations';
import { AccessTokenFormatType, SignAlgorithmType } from './custom-types';

export type ResourceServerDBEntry = {
  id: string;
  name: string;
  identifier: string;
  accessTokenTtl: number;
  accessTokenFormat: AccessTokenFormatType;
  signAlgorithm: SignAlgorithmType;
};

const guard: Guard<ResourceServerDBEntry> = z.object({
  id: z.string(),
  name: z.string(),
  identifier: z.string(),
  accessTokenTtl: z.number(),
  accessTokenFormat: z.nativeEnum(AccessTokenFormatType),
  signAlgorithm: z.nativeEnum(SignAlgorithmType),
});

export const ResourceServers: GeneratedSchema<ResourceServerDBEntry> = Object.freeze({
  table: 'resource_servers',
  tableSingular: 'resource_server',
  fields: {
    id: 'id',
    name: 'name',
    identifier: 'identifier',
    accessTokenTtl: 'access_token_ttl',
    accessTokenFormat: 'access_token_format',
    signAlgorithm: 'sign_algorithm',
  },
  fieldKeys: ['id', 'name', 'identifier', 'accessTokenTtl', 'accessTokenFormat', 'signAlgorithm'],
  guard,
});
