// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { GeneratedSchema, Guard } from '../foundations';

export type ResourceUpdate = {
  id: string;
  name: string;
  identifier: string;
  accessTokenTtl?: number;
};

export type Resource = {
  id: string;
  name: string;
  identifier: string;
  accessTokenTtl: number;
};

const guard: Guard<ResourceUpdate> = z.object({
  id: z.string(),
  name: z.string(),
  identifier: z.string(),
  accessTokenTtl: z.number().optional(),
});

export const Resources: GeneratedSchema<ResourceUpdate> = Object.freeze({
  table: 'resources',
  tableSingular: 'resource',
  fields: {
    id: 'id',
    name: 'name',
    identifier: 'identifier',
    accessTokenTtl: 'access_token_ttl',
  },
  fieldKeys: ['id', 'name', 'identifier', 'accessTokenTtl'],
  guard,
});
