// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { GeneratedSchema, Guard } from '../foundations';

export type CreateRole = {
  id: string;
  name: string;
};

export type Role = {
  id: string;
  name: string;
};

const createGuard: Guard<CreateRole> = z.object({
  id: z.string(),
  name: z.string(),
});

export const Roles: GeneratedSchema<CreateRole> = Object.freeze({
  table: 'roles',
  tableSingular: 'role',
  fields: {
    id: 'id',
    name: 'name',
  },
  fieldKeys: ['id', 'name'],
  createGuard,
});
