// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { GeneratedSchema, Guard } from '../foundations';

export type CreateRole = {
  name: string;
  description: string;
};

export type Role = {
  name: string;
  description: string;
};

const createGuard: Guard<CreateRole> = z.object({
  name: z.string(),
  description: z.string(),
});

export const Roles: GeneratedSchema<CreateRole> = Object.freeze({
  table: 'roles',
  tableSingular: 'role',
  fields: {
    name: 'name',
    description: 'description',
  },
  fieldKeys: ['name', 'description'],
  createGuard,
});
