// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import {
  AdminConsoleConfig,
  adminConsoleConfigGuard,
  GeneratedSchema,
  Guard,
} from '../foundations';

export type CreateSetting = {
  id: string;
  customDomain?: string | null;
  adminConsole: AdminConsoleConfig;
};

export type Setting = {
  id: string;
  customDomain: string | null;
  adminConsole: AdminConsoleConfig;
};

const createGuard: Guard<CreateSetting> = z.object({
  id: z.string(),
  customDomain: z.string().nullable().optional(),
  adminConsole: adminConsoleConfigGuard,
});

export const Settings: GeneratedSchema<CreateSetting> = Object.freeze({
  table: 'settings',
  tableSingular: 'setting',
  fields: {
    id: 'id',
    customDomain: 'custom_domain',
    adminConsole: 'admin_console',
  },
  fieldKeys: ['id', 'customDomain', 'adminConsole'],
  createGuard,
});
