// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { GeneratedSchema, Guard } from '../foundations';

export type CreateSignInMethod = {
  id: string;
  name: string;
  connectorId?: string | null;
};

export type SignInMethod = {
  id: string;
  name: string;
  connectorId: string | null;
};

const createGuard: Guard<CreateSignInMethod> = z.object({
  id: z.string(),
  name: z.string(),
  connectorId: z.string().nullable().optional(),
});

export const SignInMethods: GeneratedSchema<CreateSignInMethod> = Object.freeze({
  table: 'sign_in_methods',
  tableSingular: 'sign_in_method',
  fields: {
    id: 'id',
    name: 'name',
    connectorId: 'connector_id',
  },
  fieldKeys: ['id', 'name', 'connectorId'],
  createGuard,
});
