// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import {
  SignInMethodMetadata,
  signInMethodMetadataGuard,
  GeneratedSchema,
  Guard,
} from '../foundations';

export type CreateSignInMethod = {
  id: string;
  name: string;
  metadata?: SignInMethodMetadata;
};

export type SignInMethod = {
  id: string;
  name: string;
  metadata: SignInMethodMetadata;
};

const createGuard: Guard<CreateSignInMethod> = z.object({
  id: z.string(),
  name: z.string(),
  metadata: signInMethodMetadataGuard.optional(),
});

export const SignInMethods: GeneratedSchema<CreateSignInMethod> = Object.freeze({
  table: 'sign_in_methods',
  tableSingular: 'sign_in_method',
  fields: {
    id: 'id',
    name: 'name',
    metadata: 'metadata',
  },
  fieldKeys: ['id', 'name', 'metadata'],
  createGuard,
});
