// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { PasswordEncryptionMethod } from './custom-types';

export type UserDBEntry = {
  id: string;
  userName?: string;
  primaryEmail?: string;
  primaryPhone?: string;
  passwordEncrypted?: string;
  passwordEncryptionMethod?: PasswordEncryptionMethod;
  passwordEncryptionSalt?: string;
};

export const Users = Object.freeze({
  table: 'users',
  fields: {
    id: 'id',
    userName: 'user_name',
    primaryEmail: 'primary_email',
    primaryPhone: 'primary_phone',
    passwordEncrypted: 'password_encrypted',
    passwordEncryptionMethod: 'password_encryption_method',
    passwordEncryptionSalt: 'password_encryption_salt',
  },
  fieldKeys: [
    'id',
    'userName',
    'primaryEmail',
    'primaryPhone',
    'passwordEncrypted',
    'passwordEncryptionMethod',
    'passwordEncryptionSalt',
  ],
} as const);
