// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { z } from 'zod';

import { UserLogPayload, userLogPayloadGuard, GeneratedSchema, Guard } from '../foundations';
import { LogType } from './custom-types';

export type UserLogDBEntry = {
  id: string;
  userId: string;
  type: LogType;
  payload: UserLogPayload;
  createdAt: number;
};

const guard: Guard<UserLogDBEntry> = z.object({
  id: z.string(),
  userId: z.string(),
  type: z.nativeEnum(LogType),
  payload: userLogPayloadGuard,
  createdAt: z.number(),
});

export const UserLogs: GeneratedSchema<UserLogDBEntry> = Object.freeze({
  table: 'user_logs',
  tableSingular: 'user_log',
  fields: {
    id: 'id',
    userId: 'user_id',
    type: 'type',
    payload: 'payload',
    createdAt: 'created_at',
  },
  fieldKeys: ['id', 'userId', 'type', 'payload', 'createdAt'],
  guard,
});
