# From this genius: https://github.com/orgs/community/discussions/67654#discussioncomment-8038649
name: Rerun workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the workflow run to rerun (failed jobs only)'
        required: true
        type: string
jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed